// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-orb/OrbCentered.tsx": () => import("../components/mockups/landing-orb/OrbCentered.tsx"),
  "./components/mockups/landing-orb/OrbOffset.tsx": () => import("../components/mockups/landing-orb/OrbOffset.tsx"),
  "./components/mockups/landing-orb/OrbSleeve.tsx": () => import("../components/mockups/landing-orb/OrbSleeve.tsx")
};
